# Trabalho ENGA75

### Autor: Allan Almeida

In [1]:
from ur5 import UR5, forward_kinematics
from math import pi
import numpy as np
ur5 = UR5()
PI = pi

Inicializando a classe UR5...
Inicializando os nós e handles...
Pronto!


## Etapa A1

Implementar a Cinemática Direta e Inversa do Robô UR5. Validar a modelagem com o auxílio do
simulador para um conjunto de valores das variáveis das juntas (Cinemática Direta) e para um conjunto de
posições e orientações da garra (Cinemática Inversa)

#### Cinemática Direta

In [2]:
def validate_fk(ang):
    fk, _ = forward_kinematics(ang)    # Calcular cinemática direta a partir dos ângulos
    print('Cinemática Direta: ')
    print(fk)
    ur5.move_to_config(ang)     # Mover para a posição
    print('Ground Truth: ')
    gt = ur5.get_ground_truth()     # Obter Ground Truth
    print(gt)
    print('Erro: ', np.linalg.norm(fk-gt)/np.linalg.norm(gt)*100, '%')  # Calcular e printar erro

In [6]:
validate_fk([.5*PI, .05*PI, .45*PI, 0, -.5*PI, .5*PI])

Cinemática Direta: 
[[ 6.12323400e-17 -1.00000000e+00  1.22464680e-16  1.09150000e-01]
 [-1.00000000e+00 -6.12323400e-17 -1.03616896e-16 -5.53384648e-01]
 [ 1.17060840e-16 -1.22464680e-16 -1.00000000e+00  3.03016545e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iterações totais:  157
Ground Truth: 
[[ 1.89973260e-05 -9.99999990e-01  1.39024490e-04  1.34025113e-01]
 [-9.99999999e-01 -1.90036843e-05 -4.57336868e-05 -5.58519465e-01]
 [ 4.57363284e-05 -1.39023621e-04 -9.99999989e-01  3.58208056e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Erro:  2.8774514057411085 %


In [13]:
validate_fk([-.5*PI, -.05*PI, -.45*PI, 0, .5*PI, .5*PI])

Cinemática Direta: 
[[ 6.12323400e-17 -1.00000000e+00 -1.22464680e-16 -1.09150000e-01]
 [-1.00000000e+00 -6.12323400e-17 -1.15059273e-16 -5.53384648e-01]
 [ 1.29870087e-16  1.22464680e-16 -1.00000000e+00  3.03016545e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iterações totais:  157
Ground Truth: 
[[ 4.32548576e-05 -9.99999997e-01 -6.86566799e-05 -1.33900792e-01]
 [-9.99999563e-01 -4.31907140e-05 -9.33992355e-04 -5.58492594e-01]
 [ 9.33989387e-04  6.86970496e-05 -9.99999561e-01  3.58631858e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Erro:  2.893786129919564 %


In [14]:
ur5.actuate_gripper(close=0)

Iterações totais:  63
2.0160000000000053


In [15]:
ur5.move_to_config([0, 0, 0, 0, 0, 0])

Iterações totais:  157


(5.023999999999994, 0.06215621800345908, 0.02097129041154536)

In [7]:
ur5.move_to_config([.5*pi, .05*pi, .45*pi, 0, -.5*pi, .5*pi])

Iterações totais:  157


(5.024000000000001, 0.10390928968378059, 0.032766049589412795)

In [11]:
ur5.move_to_config([.4*pi, .18*pi, .57*pi, 0.25*pi, 0.8, PI/2])

Iterações totais:  157


(5.024000000000001, 0.13436096759997243, 0.03326078798164792)

In [ ]:
# bottle = supervisor.getFromDef('bottle')

In [ ]:
# bottle.getField('translation').setSFVec3f([-1.467559345817077, 1.7836801495521285e-06, 0.9004484925267724])

In [ ]:
# bottle.getField('translation').getSFVec3f()